#!/bin/bash

usage()
{
cat << EOF
usage: maketitle [options] title

Prints out a decorated title.

Options:
  -h | --help     Print out the help documentation
  -c | --color    Followed by special echo command for printing, such as
                  echo_blue

Arguments:
  title           word or phrase making up the title

EOF
}

ECHOCOM="echo"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
	-h|--help)
  usage
  exit
  ;;
	-c|--color)
	ECHOCOM="$2"
	shift
  shift
	;;
  *)    # unknown option
	POSITIONAL+=("$1") # save it in an array for later
  shift # past argument
  ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

WSPADDING="        "
PADCHAR="="

echoPaddingWithLengthOf() {
  PC=$1
  shift
  STR="$@"
  SPACELESS=(${STR// /-})
  STRLIST=`echo $SPACELESS | fold -w1`
  for i in $STRLIST; do
    ESTR="$ECHOCOM -en '${PC}'"
    eval "$ESTR"
  done
}

TITLEBUFFER1="....."
TITLEBUFFER2=".."
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echoPaddingWithLengthOf $PADCHAR "$@"
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER2
echo
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echo -n " $@ "
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echo
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echoPaddingWithLengthOf $PADCHAR "$@"
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER1
echoPaddingWithLengthOf $PADCHAR $TITLEBUFFER2
echo
