#!/bin/bash

##############
# HELP DISPLAY
##############

usage()
{
cat << EOF
usage: myports

Execute this command anywhere to get current port information that you actually find useful.

EOF
}

#################
# PARSE ARGUMENTS
#################

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
    usage
    exit
    ;;
    *)    # unknown option
  POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

#########
# EXECUTE
#########

for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
    (
        syspath="${sysdevpath%/dev}"
        devname="$(udevadm info -q name -p $syspath)"
        [[ "$devname" == "bus/"* ]] && continue
        eval "$(udevadm info -q property --export -p $syspath)"
        [[ -z "$ID_SERIAL" ]] && continue
        echo_yellow -n "/dev/$devname"
        echo " - $ID_SERIAL"
    )
done
