#!/bin/bash

#################################################
# GET DIRECTORY OF THIS SCRIPT TO ACCESS TEMPLATE
#################################################

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#################################
# GET EDIT DIRECTORY IF IT EXISTS
#################################

if [ -z $1 ]; then
  EDITDIR="${PWD}"
else
  EDITDIR="${PWD}/$1"
fi

#################
# EXECUTE COMMAND
#################

cd "$EDITDIR"
terminator -l A2 </dev/null &>/dev/null &
